apiVersion: v1
kind: Service
metadata:
  name: kafka-kube-service
  namespace: dn
spec:
  type: ClusterIP
  selector:
    app: kafka # Matches your Kafka pod's label
  ports:
    - port: 80        # Service port
      targetPort: 9092  # Container port
