apiVersion: v1
kind: Service
metadata:
  name: kafka-kube-service
  labels:
    app: kafka-kube-service
spec:
  selector:
    app: kafka-pod  # Matches your Kafka pod's label
  ports:
    - port: 9092        # Service port
      targetPort: 9092  # Container port
